exclude: "^docs/|/migrations/|devcontainer.json|unfold/models.py"
default_stages: [commit]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-ast
      - id: check-merge-conflict
      - id: forbid-new-submodules
        args:
          - --autofix
          - --indent=4
          - --no-ensure-ascii
          - --no-sort-keys
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md] # Preserve Markdown hard linebreaks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter
      - id: ruff-format

  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.19.0
    hooks:
      - id: slotscheck
        exclude: test_*|docs|migrations|scripts
        entry: env PYTHONPATH=. slotscheck

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        exclude: scripts/
        additional_dependencies:
          - passlib[argon2]
          - asyncpg
          - asyncpg-stubs
          - litestar[jinja,jwt,redis,structlog]
          - advanced-alchemy[uuid]>=0.10.0
          - litestar-granian
          - litestar-vite>=0.1.21
          - litestar-saq
          - types-python-jose
          - types-click
          - types-redis
          - types-passlib
          - types-click
          - types-PyYAML
          - types-aiofiles
          - types-requests
