[tool.poetry]
name = "ergostar"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
litestar = {extras = ["jinja", "sqlalchemy", "standard", "structlog"], version = "^2.9.0"}
litestar-vite = "^0.1.22"
pydantic = "^2.7.4"
pre-commit = "^3.7.1"
pydantic-settings = "^2.3.3"
sqlalchemy = "^2.0.30"
redis = {extras = ["hiredis"], version = "^5.0.6"}


[tool.poetry.group.dev.dependencies]
aiosqlite = "^0.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
