# type: ignore
"""

Revision ID: 1af6cef851a2
Revises: 
Create Date: 2024-07-28 09:36:53.036794+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = '1af6cef851a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing__home_page',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subtitle_1', sa.String(length=255), nullable=False),
    sa.Column('subtitle_2', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('you_get_label', sa.String(length=255), nullable=False),
    sa.Column('you_get_title', sa.String(length=255), nullable=False),
    sa.Column('you_get_subtitle', sa.String(length=255), nullable=False),
    sa.Column('you_get_block_1_title', sa.String(length=255), nullable=False),
    sa.Column('you_get_block_1_description', sa.Text(), nullable=False),
    sa.Column('you_get_block_1_feather_icon', sa.String(length=40), nullable=False),
    sa.Column('you_get_block_2_title', sa.String(length=255), nullable=False),
    sa.Column('you_get_block_2_description', sa.Text(), nullable=False),
    sa.Column('you_get_block_2_feather_icon', sa.String(length=40), nullable=False),
    sa.Column('you_get_block_3_title', sa.String(length=255), nullable=False),
    sa.Column('you_get_block_3_description', sa.Text(), nullable=False),
    sa.Column('you_get_block_3_feather_icon', sa.String(length=40), nullable=False),
    sa.Column('you_get_block_4_title', sa.String(length=255), nullable=False),
    sa.Column('you_get_block_4_description', sa.Text(), nullable=False),
    sa.Column('you_get_block_4_feather_icon', sa.String(length=40), nullable=False),
    sa.Column('get_started_label', sa.String(length=255), nullable=False),
    sa.Column('get_started_title', sa.String(length=255), nullable=False),
    sa.Column('get_started_array', sa.String(length=255), nullable=False),
    sa.Column('get_started_description', sa.Text(), nullable=False),
    sa.Column('get_started_lower_title', sa.String(length=255), nullable=False),
    sa.Column('get_started_button_text', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landing__home_page'))
    )
    op.create_table('landing__settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('footer_description', sa.Text(), nullable=True),
    sa.Column('footer_rights', sa.Text(), nullable=False),
    sa.Column('url_login', sa.String(length=255), nullable=False),
    sa.Column('url_api_docs', sa.String(length=255), nullable=False),
    sa.Column('url_register', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landing__settings'))
    )
    op.create_table('landing__snippet',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tab', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('code_language', sa.String(length=20), nullable=False),
    sa.Column('feather_icon', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landing__snippet'))
    )
    with op.batch_alter_table('landing__snippet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landing__snippet_is_active'), ['is_active'], unique=False)

    op.create_table('landing__solution',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_carousel', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_top_active', sa.Boolean(), nullable=False),
    sa.Column('is_carousel_active', sa.Boolean(), nullable=False),
    sa.Column('docs_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landing__solution'))
    )
    with op.batch_alter_table('landing__solution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landing__solution_is_carousel_active'), ['is_carousel_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_landing__solution_is_top_active'), ['is_top_active'], unique=False)

    op.create_table('subscriptions__plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=False),
    sa.Column('monthly_price', sa.Integer(), nullable=True),
    sa.Column('annual_price', sa.Integer(), nullable=True),
    sa.Column('monthly_requests_limit', sa.Integer(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('rate_period', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions__plans'))
    )
    with op.batch_alter_table('subscriptions__plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions__plans_is_public'), ['is_public'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions__plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions__plans_is_public'))

    op.drop_table('subscriptions__plans')
    with op.batch_alter_table('landing__solution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landing__solution_is_top_active'))
        batch_op.drop_index(batch_op.f('ix_landing__solution_is_carousel_active'))

    op.drop_table('landing__solution')
    with op.batch_alter_table('landing__snippet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landing__snippet_is_active'))

    op.drop_table('landing__snippet')
    op.drop_table('landing__settings')
    op.drop_table('landing__home_page')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
