# type: ignore
"""

Revision ID: 535d2890bb10
Revises: 53fa7ca7a5a1
Create Date: 2024-07-07 17:22:47.400030+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = '535d2890bb10'
down_revision = '53fa7ca7a5a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing__home_page', schema=None) as batch_op:
        batch_op.alter_column('you_get_subtitle',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=False,
                              existing_server_default=sa.text(
                                  "'Our API services are designed to help you build powerful and versatile applications.'::character varying"))
        batch_op.alter_column('get_started_description',
                              existing_type=sa.TEXT(),
                              nullable=False,
                              existing_server_default=sa.text(
                                  "'Ergolon API saves you tons of hard work and time by providing you with a wide range of services to enhance your applications.'::text"))
        batch_op.alter_column('get_started_lower_title',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=False,
                              existing_server_default=sa.text("'Available right Now'::character varying"))
        batch_op.alter_column('get_started_button_text',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=False,
                              existing_server_default=sa.text("'Get it Now'::character varying"))

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing__home_page', schema=None) as batch_op:
        batch_op.alter_column('get_started_button_text',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=True,
                              existing_server_default=sa.text("'Get it Now'::character varying"))
        batch_op.alter_column('get_started_lower_title',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=True,
                              existing_server_default=sa.text("'Available right Now'::character varying"))
        batch_op.alter_column('get_started_description',
                              existing_type=sa.TEXT(),
                              nullable=True,
                              existing_server_default=sa.text(
                                  "'Ergolon API saves you tons of hard work and time by providing you with a wide range of services to enhance your applications.'::text"))
        batch_op.alter_column('you_get_subtitle',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=True,
                              existing_server_default=sa.text(
                                  "'Our API services are designed to help you build powerful and versatile applications.'::character varying"))

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
