# type: ignore
"""

Revision ID: 48fec3ec3c18
Revises: ce11da60f13e
Create Date: 2024-06-24 07:38:24.551467+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = '48fec3ec3c18'
down_revision = 'ce11da60f13e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing__home_page',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('subtitle_1', sa.String(length=255), nullable=False),
    sa.Column('subtitle_2', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('you_get_label', sa.String(length=255), server_default='Futures', nullable=False),
    sa.Column('you_get_title', sa.String(length=255), server_default='What you will get with Ergostar API', nullable=False),
    sa.Column('you_get_subtitle', sa.String(length=255), server_default='Our API services are designed to help you build powerful and versatile applications.', nullable=True),
    sa.Column('you_get_block_1_title', sa.String(length=255), server_default='Dashboard', nullable=False),
    sa.Column('you_get_block_1_description', sa.Text(), server_default="Get a bird's eye view of your account and manage your API keys, usage, and billing information.", nullable=False),
    sa.Column('you_get_block_1_feather_icon', sa.String(length=40), server_default='pie-chart', nullable=False),
    sa.Column('you_get_block_2_title', sa.String(length=255), server_default='Save money', nullable=False),
    sa.Column('you_get_block_2_description', sa.Text(), server_default='Save money by using our versatile range of API services.', nullable=False),
    sa.Column('you_get_block_2_feather_icon', sa.String(length=40), server_default='dollar-sign', nullable=False),
    sa.Column('you_get_block_3_title', sa.String(length=255), server_default='Boost Performance', nullable=False),
    sa.Column('you_get_block_3_description', sa.Text(), server_default="Boost your app's performance and capabilities by integrating our APIs.", nullable=False),
    sa.Column('you_get_block_3_feather_icon', sa.String(length=40), server_default='trending-up', nullable=False),
    sa.Column('you_get_block_4_title', sa.String(length=255), server_default='Documentation', nullable=False),
    sa.Column('you_get_block_4_description', sa.Text(), server_default='Access our comprehensive documentation to learn more about our API services.', nullable=False),
    sa.Column('you_get_block_4_feather_icon', sa.String(length=40), server_default='book', nullable=False),
    sa.Column('get_started_label', sa.String(length=255), server_default='Get Started', nullable=False),
    sa.Column('get_started_title', sa.String(length=255), server_default='Ergolon saves', nullable=False),
    sa.Column('get_started_array', sa.String(length=255), server_default='"Time", "Money", "Effort"', nullable=False),
    sa.Column('get_started_description', sa.Text(), server_default='Ergolon API saves you tons of hard work and time by providing you with a wide range of services to enhance your applications.', nullable=True),
    sa.Column('get_started_lower_title', sa.String(length=255), server_default='Available right Now', nullable=True),
    sa.Column('get_started_button_text', sa.String(length=255), server_default='Get it Now', nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landing__home_page'))
    )
    op.create_table('landing__settings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('footer_description', sa.Text(), nullable=True),
    sa.Column('footer_rights', sa.Text(), nullable=False),
    sa.Column('url_login', sa.String(length=255), nullable=False),
    sa.Column('url_api_docs', sa.String(length=255), nullable=False),
    sa.Column('url_register', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landing__settings'))
    )
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landing__settings')
    op.drop_table('landing__home_page')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
